// Parody billboards, posters and signs ("mauvaise copie assumée"). Each gag = a frame prop (baked with the decor)
// + a textured face (one small mesh). Some gags also drop an extra prop (the camel on holiday, the sleeping cat…).
import { LUMEN } from './env-util.js';

const { teal, mint, cream, coral, gold, night, comet, dawn, aurora } = LUMEN;

// type: billboard (big, 5.2×2.6 face) | poster (small, 1.8×1.3 face on two posts)
export const GAGS = {
  notcrash: { type: 'billboard', icon: 'nobandicoot', bg: cream, fg: night, accent: coral,
    fr: ['Ceci n\'est pas une île de Crash.', 'Nos avocats insistent.'], en: ['This is not a Crash island.', 'Our lawyers insist.'] },
  lawyers: { type: 'poster', bg: 0xffffff, fg: night, accent: teal,
    fr: ['AVIS LÉGAL', 'Toute ressemblance avec un marsupial', 'existant serait purement fortuite.'], en: ['LEGAL NOTICE', 'Any resemblance to an actual marsupial', 'is purely coincidental.'] },
  sunscreen: { type: 'billboard', icon: 'sun', bg: 0xffe9b8, fg: night, accent: coral,
    fr: ['Crème Cortisol indice 0', 'Brûlez en toute sérénité.', 'Testée sur aucun bandicoot.'], en: ['Cortisol Sunscreen SPF 0', 'Burn with total serenity.', 'Tested on zero bandicoots.'] },
  nobandicoot: { type: 'poster', icon: 'nobandicoot', bg: 0xffffff, fg: night, accent: 0xd92b2b, style: 'sign',
    fr: ['Interdit aux', 'bandicoots', '(les renards, ça passe)'], en: ['No', 'bandicoots', '(foxes are fine)'] },
  moonroll: { type: 'poster', bg: gold, fg: night, accent: night, style: 'sign',
    fr: ['ATTENTION', 'Lune qui roule', 'sur 2 km'], en: ['CAUTION', 'Rolling moon', 'next 2 km'] },
  jungletm: { type: 'billboard', bg: mint, fg: night, accent: teal,
    fr: ['Jungle™', 'Copie certifiée non conforme', 'Arbres garantis 100 % polygones'], en: ['Jungle™', 'Certified non-compliant copy', 'Trees guaranteed 100% polygons'] },
  okutips: { type: 'poster', bg: dawn, fg: night, accent: coral,
    fr: ['Conseil d\'Oku Oku', 'Pour ne pas tomber :', 'ne pas tomber.'], en: ['Oku Oku\'s tip', 'To avoid falling:', 'do not fall.'] },
  lilypads: { type: 'billboard', bg: aurora, fg: night, accent: teal,
    fr: ['Nénuphars Express', 'Garantis 30 % flottants', 'Remboursés si vous coulez*'], en: ['Lily Pad Express', 'Guaranteed 30% floating', 'Refund if you sink*'] },
  noswim: { type: 'poster', bg: 0xffffff, fg: night, accent: 0x2a6fd0, style: 'sign',
    fr: ['Baignade interdite', 'Natation aussi.', 'Flotter : toléré'], en: ['No bathing', 'No swimming either.', 'Floating: tolerated'] },
  camel: { type: 'poster', icon: 'camel', bg: cream, fg: night, accent: coral, extra: 'camel_vacation',
    fr: ['Chameau en vacances', 'Ne pas déranger', 'Retour : jamais'], en: ['Camel on holiday', 'Do not disturb', 'Back: never'] },
  mirage: { type: 'poster', bg: 0xf6e0b0, fg: night, accent: teal, style: 'sign',
    fr: ['Oasis à 2 km*', '*mirage', 'Dernière oasis avant mirage'], en: ['Oasis 2 km ahead*', '*mirage', 'Last oasis before mirage'] },
  tozeur: { type: 'billboard', bg: 0xf0b070, fg: night, accent: coral,
    fr: ['Dunes de Tozeur', 'Elles chantent (faux).', 'Bouchons d\'oreilles conseillés'], en: ['Tozeur Dunes', 'They sing (off-key).', 'Earplugs recommended'] },
  cortisol: { type: 'billboard', icon: 'cortisol', bg: comet, fg: night, accent: coral,
    fr: ['Cortisol Industries', 'Du stress de qualité depuis 1996.', 'Votre angoisse, notre métier.'], en: ['Cortisol Industries', 'Quality stress since 1996.', 'Your anxiety is our business.'] },
  carpets: { type: 'poster', bg: 0xe8c898, fg: night, accent: teal,
    fr: ['Tapis volants', 'Contrôle technique obligatoire', 'Franges non comprises'], en: ['Flying carpets', 'Mandatory MOT', 'Fringes not included'] },
  sales: { type: 'poster', bg: coral, fg: 0xffffff, accent: gold,
    fr: ['SOLDES !', 'Tout doit stresser', '-70 % de sérénité'], en: ['SALE!', 'Everything must stress', '-70% serenity'] },
  catnap: { type: 'poster', icon: 'cat', bg: 0xffffff, fg: 0x1a4fa0, accent: 0x2a6fd0, extra: 'cat_wall',
    fr: ['Chat en sieste', 'Revenez à 17 h', '(ou demain)'], en: ['Cat napping', 'Come back at 5 pm', '(or tomorrow)'] },
  bluepaint: { type: 'poster', bg: 0xfbf8f0, fg: 0x1a4fa0, accent: 0x2a6fd0,
    fr: ['Peinture bleue', 'Rupture de stock (encore)', 'Merci pour votre patience'], en: ['Blue paint', 'Out of stock (again)', 'Thanks for your patience'] },
  cafe: { type: 'billboard', bg: 0xfbf8f0, fg: 0x1a4fa0, accent: 0x2a6fd0,
    fr: ['Café des Délices', 'Thé à la menthe & pignons', 'Bandicoots : non. Renards : oui.'], en: ['Café des Délices', 'Mint tea & pine nuts', 'Bandicoots: no. Foxes: yes.'] },
  penguins: { type: 'poster', icon: 'penguin', bg: 0xe8f4ff, fg: night, accent: 0x2a6fd0, style: 'sign',
    fr: ['Pingouins grognons', 'Ne pas nourrir.', 'Ils mordent. Fort.'], en: ['Grumpy penguins', 'Do not feed.', 'They bite. Hard.'] },
  slide: { type: 'billboard', bg: 0xd8f0ff, fg: night, accent: coral,
    fr: ['Glissade gratuite !', 'Chute offerte.', 'Freins en option'], en: ['Free sliding!', 'Falling included.', 'Brakes sold separately'] },
  yeti: { type: 'billboard', bg: 0xffffff, fg: night, accent: comet,
    fr: ['Yéti Influenceur', 'Abonne-toi ou je t\'écrase', '12 abonnés (dont sa mère)'], en: ['Yeti Influencer', 'Subscribe or get squashed', '12 followers (incl. his mum)'] },
  crystals: { type: 'poster', bg: comet, fg: night, accent: teal, style: 'sign',
    fr: ['Cristaux © Cortisol', 'Ne pas lécher.', 'Même un peu.'], en: ['Crystals © Cortisol', 'Do not lick.', 'Not even a little.'] },
  echo: { type: 'poster', bg: 0x9fe8e0, fg: night, accent: comet,
    fr: ['ÉCHO… écho… écho…', 'Merci de crier', 'moins fort'], en: ['ECHO… echo… echo…', 'Please scream', 'more quietly'] },
  aurora_trial: { type: 'billboard', bg: 0x2a3a6a, fg: 0xffffff, accent: aurora,
    fr: ['Aurores boréales', 'Version d\'essai : 30 jours', 'Activez votre licence !'], en: ['Northern lights', '30-day free trial', 'Activate your licence!'] },
  accidents: { type: 'billboard', bg: gold, fg: night, accent: night,
    fr: ['Jours sans accident :', '0', 'Record à battre : 0'], en: ['Days without accident:', '0', 'Record to beat: 0'] },
  stressotron: { type: 'billboard', icon: 'cortisol', bg: 0xffffff, fg: night, accent: 0xe94f4f,
    fr: ['Stressotron 3000', '40 % de soucis en plus !', 'Satisfait ou angoissé'], en: ['Stressotron 3000', '40% more worries!', 'Satisfied or anxious'] },
  labban: { type: 'poster', icon: 'nobandicoot', bg: 0xffffff, fg: night, accent: 0xd92b2b, style: 'sign',
    fr: ['Laboratoire', 'Interdit aux bandicoots', 'et aux gens détendus'], en: ['Laboratory', 'No bandicoots', 'and no relaxed people'] },
  redbutton: { type: 'poster', bg: 0xffffff, fg: 0xd92b2b, accent: 0xd92b2b,
    fr: ['NE PAS APPUYER', 'sur le bouton rouge', '(il n\'y a pas de bouton rouge)'], en: ['DO NOT PRESS', 'the red button', '(there is no red button)'] },
  rats: { type: 'poster', bg: mint, fg: night, accent: teal,
    fr: ['Rats de labo recherchés', 'Blouse fournie', 'Fromage non contractuel'], en: ['Lab rats wanted', 'Lab coat provided', 'Cheese not guaranteed'] },
  cardboard: { type: 'billboard', icon: 'rocket', bg: 0xe8c898, fg: night, accent: coral,
    fr: ['Fusées en Carton SARL', 'Homologuées par personne.', 'Ne pas utiliser sous la pluie'], en: ['Cardboard Rockets Ltd', 'Certified by nobody.', 'Do not use in the rain'] },
  spacestress: { type: 'billboard', bg: night, fg: 0xffffff, accent: comet,
    fr: ['Dans l\'espace,', 'personne ne vous entend stresser.', 'Sauf le Dr Cortisol.'], en: ['In space,', 'no one can hear you stress.', 'Except Dr Cortisol.'] },
  stresstower: { type: 'billboard', icon: 'cortisol', bg: 0x3a2040, fg: 0xffffff, accent: coral,
    fr: ['Tour du Stress', '99 étages de soucis', 'Vue imprenable sur vos angoisses'], en: ['Stress Tower', '99 floors of worries', 'Stunning view of your anxieties'] },
  elevator: { type: 'poster', bg: 0xffffff, fg: night, accent: gold, style: 'sign',
    fr: ['Ascenseur en panne', 'depuis 1996', 'Prenez les plateformes'], en: ['Elevator out of order', 'since 1996', 'Please use the platforms'] },
  crabking: { type: 'billboard', icon: 'crab', bg: dawn, fg: night, accent: coral,
    fr: ['Papa Crabe Royal', 'Sa Majesté pince.', 'Révérence obligatoire'], en: ['Royal Papa Crab', 'His Majesty pinches.', 'Bowing mandatory'] },
  arena: { type: 'billboard', bg: gold, fg: night, accent: coral,
    fr: ['Arène officielle', 'Billets non remboursables', 'Boss non plus'], en: ['Official arena', 'Non-refundable tickets', 'Non-refundable boss too'] },
  djinn: { type: 'billboard', bg: comet, fg: night, accent: gold,
    fr: ['Djinn de la Lampe', 'Trois vœux, zéro politesse.', 'Frottez à vos risques'], en: ['Genie of the Lamp', 'Three wishes, zero manners.', 'Rub at your own risk'] },
  finalboss: { type: 'billboard', icon: 'cortisol', bg: 0xffffff, fg: night, accent: 0xe94f4f,
    fr: ['Dr Néo Cortisol', 'Employé du mois', '(tous les mois)'], en: ['Dr Neo Cortisol', 'Employee of the month', '(every month)'] },
  goldnotcrash: { type: 'billboard', icon: 'sock', bg: 0xfff0c0, fg: night, accent: gold,
    fr: ['Tout ce qui brille', 'n\'est pas Crash.', 'Mais ça brille quand même.'], en: ['All that glitters', 'is not Crash.', 'But it does glitter.'] },
  socks: { type: 'poster', icon: 'sock', bg: comet, fg: night, accent: gold,
    fr: ['Chaussettes dorées', 'Lavage à 30° uniquement', 'Ne pas mélanger'], en: ['Golden socks', 'Wash at 30° only', 'Do not mix'] },
};

/** text spec for signTexture */
export function gagSpec(id, lang = 'fr', override = null) {
  const g = GAGS[id] || GAGS.notcrash;
  const lines = override ? [].concat(override) : (g[lang] || g.fr);
  const big = g.type === 'billboard';
  return {
    title: lines[0], sub: lines[1], small: lines[2],
    bg: g.bg, fg: g.fg, accent: g.accent, icon: g.icon, style: g.style || (big ? 'board' : 'poster'),
    w: big ? 720 : 512, h: big ? 320 : 384,
  };
}
